### ISSUE TITLE
support for -geometry

### ISSUE THREAD

**Issue by maxime-esa** [dkogan/feedgnuplot#10]
The original implementation from Thanassis Tsiodras contained a way to pass the -geometry option to gnuplot, in order to set the plotting window size and position.
Could you add this feature in your Perl script too? 
The format is standard : when you call gnuplot, simply add -geometry to the parameter list:
$geometry='320x240+0+0'

open PIPE, "|gnuplot $dopersist -geometry $geometry" or die "Can't initialize gnuplot\n";

Thank you and congratulation for this project
Maxime

**Comment by unhammer** [comment]
I don't see any effect of this option, e.g. trying `feedgnuplot --geometry '320x240+0+0'` gives me the same tiny window as `feedgnuplot --geometry '920x1240+0+0'`  – is my syntax wrong?

**Comment by dkogan** [comment]
Your syntax is right, but this option applies only to the 'x11' gnuplot terminal. This isn't the gnuplot default anymore, so unless you specifically asked for it, that's not what you're using, and this option does nothing. Put

```
set terminal x11 noenhanced
```

into ~/.gnuplot to default to the 'x11' terminal. To control the window size for any other terminal, ask for the terminal explicitly, with the options specifying the size. For instance

```
--terminal 'qt size 1024,768'
```

I updated the documentaiton

**Comment by unhammer** [comment]
Thanks! That makes it  much nicer =D
