### ISSUE TITLE
Histogram Support

### ISSUE THREAD

**Issue by eschulte** [dkogan/feedgnuplot#11]
This is a feature request.

I'd love to see support for plotting histograms with feedgnuplot.  I often want to see a distribution of command-line data.  Would it be difficult to add a --hist option which default to breaking the input data into say 100 boxes, and then takes an optional argument to customize the number of boxes.

If I find the time I'll take a look at this, and if my Perl still works I'll submit a patch (but those are both big IFs).

Thanks for providing this fantastic tool!

**Comment by falves1** [comment]
I need to know there is somebody supporting this tool. I have some question about histograms.

**Comment by dkogan** [comment]
Generally, you ask the question, and somebody replies, if they know something. Please make a new issue.

**Comment by falves1** [comment]
I spent hours tying and couldn't a simple histogram with command like this
feedgnuplot --points --histo 0,1 --curvestyleall 'with boxes' --bin 2000 --histstyle cum --terminal 'dumb 80,40'
![image](https://user-images.githubusercontent.com/6633287/107136405-d7539f00-68d0-11eb-925d-5c3d136ed6c2.png)
how do you do this in plain terminal or for html? I actually need to show it in htlm as an image or a table,etc.

**Comment by dkogan** [comment]
To include into a webpage, output svg (for vector images) or png (for rasterized images). For instance:

```
seq 1000 | awk '{print rand()}' | feedgnuplot --histo 0 --binwidth 0.1 --hardcopy /tmp/tst.png
```
![tst](https://user-images.githubusercontent.com/170011/107179592-bef48a80-698b-11eb-81bd-bfeefe9a95a2.png)

For your specific case, send me the data if you want me to look at it. But in a new issue. I will not reply in this issue anymore.
