### ISSUE TITLE
Nothing is happening

### ISSUE THREAD

**Issue by nh2** [dkogan/feedgnuplot#13]
I run (on Ubuntu 13.04):

```
seq 5 | awk '{print 2*$1, $1*$1}' | bin/feedgnuplot --domain
```

No output, no windows.

**Comment by csolorio** [comment]
I know this is closed, but I was wondering whether experiencing the same... But in windows could be caused by gnuplot version or simply, perl doesn't behave the same between linux or windows...?

**Comment by dkogan** [comment]
I don't use Windows, so can't help you there at all. But if you're not able to get anything plotted with feedgnuplot, the first test is to make sure that gnuplot itself is functional.
