### ISSUE TITLE
exit command does not work.

### ISSUE THREAD

**Issue by bigblindbais** [dkogan/feedgnuplot#20]
I have feedgnuplot version 1.34 and can't seem to get the exit command to work properly (only tried gnome-terminal with zsh and bash).

Here is the command I run:
```bash
feedgnuplot --lines --stream 0 --exit
1
2
3
1
replot
exit
...
<CTRL-D>
```

What I expect:
 * when I run exit, I expect the program to exit (i.e. the window remains, but stdin closes, and a new terminal prompt appears)
 * given that the previous didn't exit the program, when I press CTRL-D, I expect the program to exit (i.e. as above).

What happens:
 * when I run exit, the program doesn't end (the program stops interpreting new commands in the stdin, but I still have the stdin open, which I can now only exit using CTRL-C).
 * when I press CTRL-D, the program doesn't end (the stdin remains open, but I can't type anything into it, so maybe it's better said that simply I don't return to the prompt. I need to close it using CTRL-C).

CTRL-D works when I use it on an instance of feedgnuplot which doesn't have the --stream flag set (still requires --exit).
exit never works.

Let me know if I need to give out more details.
Best,

**Comment by dkogan** [comment]
closing. presumably the reporter was satisfied
