### ISSUE TITLE
Feature request: --y3

### ISSUE THREAD

**Issue by vi** [dkogan/feedgnuplot#25]
`--y4` and so on.

Additional axes should be displayed also at left and at right of the plot, matching in colour of the data points.

**Comment by dkogan** [comment]
Hi. This is something that gnuplot very explicitly does not support, so I cannot add it. You can suggest this feature to the gnuplot project, but I doubt it'll be implemented any time soon. Hope you can make do with what is available.

**Comment by vi** [comment]
Do you know some workarounds?

The only one I know is pre-processing values, bringing them approximately to the same scale as other data line. But that is hacky and the result looks unprofessional.

**Comment by dkogan** [comment]
Vitaly Shukela <notifications@github.com> writes:

> Do you know some workarounds?
>
> The only one I know is pre-processing values, bringing them
> approximately to the same scale as other data line. But that is hacky
> and the result looks unprofessional.

Gnuplot cannot do this, but some other tools can. For instance:

  http://matplotlib.org/examples/axes_grid/demo_parasite_axes2.html

I think that looks weird and unprofessional too, however, so in my mind
it's not really any better. If you find some perfect solution, tell me.
