### ISSUE TITLE
The README.pod is broken

### ISSUE THREAD

**Issue by vladimiroltean** [dkogan/feedgnuplot#30]
Just letting you know :)

**Comment by dkogan** [comment]
Vladimir Oltean <notifications@github.com> writes:

> Just letting you know :)

Thanks for letting me know. It IS broken, but I didn't break it :)

Github broke their POD handling again. I'll complain to them.

**Comment by vladimiroltean** [comment]
Ok, updated the title then.

**Comment by dkogan** [comment]
I guess they fixed it. Closing bug.
