### ISSUE TITLE
Perl related dependency missing?

### ISSUE THREAD

**Issue by csolorio** [dkogan/feedgnuplot#39]
What specific package could my distro be missing if I get the following message when trying to execute feedgnuplot?

Can't locate List/MoreUtils.pm in @INC (@INC contains: /usr/local/lib64/perl5 /usr/local/share/perl5 /usr/lib64/perl5/vendor_perl /usr/share/perl5/vendor_perl /usr/lib64/perl5 /usr/share/perl5 .) at /usr/local/bin/feedgnuplot line 12

Thanks

**Comment by dkogan** [comment]
You're missing List::MoreUtils

The dependency is declared, I think. Are you just trying to run from source, or did you "install" feedgnplot somehow?

**Comment by csolorio** [comment]
Ok. I'm getting the dependencies. Since my distro (CentOS) doesn't have feedgnuplot as a package, I'm just using the file in the bin folder. Sorry about that :P

I just needed to install the following packages, instead of the whole perl/perl-core package.
For this one: perl-List-MoreUtils
For Time/Piece.pm: perl-Time-Piece

Thanks for the prompt response!
