### ISSUE TITLE
[Q] How do I plot in the terminal?

### ISSUE THREAD

**Issue by NightMachinary** [dkogan/feedgnuplot#40]
Using `feedgnuplot --stream --terminal 'dumb 120,30' --lines` causes continuous  new plots to be outputted, not updating a single plot:
![image](https://user-images.githubusercontent.com/36224762/97085774-58da3680-162c-11eb-8bfd-c32fbb7c3fd3.png)

I tried `--terminal 'domterm'` which hanged, and `--terminal 'xterm'`:
```
Warning: empty y range [1.8:1.8], adjusting to [1.782:1.818]
!r#W!r>U!r#W!r$B!r>U!r>J!g!C 1.78
$j#W$j>U$j#W$j$B$j>U$j>J# U 1.785
'b#W'b>U'b#W'b$B'b>U'b>J&w!C 1.79
)z#W)z>U)z#W)z$B)z>U)z>J)o U 1.795
,r#W,r>U,r#W,r$B,r>U,r>J,g!Q 1.8
/j#W/j>U/j#W/j$B/j>U/j>J. U 1.805
2b#W2b>U2b#W2b$B2b>U2b>J1w!C 1.81
4z#W4z>U4z#W4z$B4z>U4z>J4o U 1.815
7r#W7r>U7r#W7r$B7r>U7r>J7g!C 1.82
...
```

**Comment by dkogan** [comment]
The "dumb" terminal is dumb: i.e. it can only print text. It cannot go
back, and overwrite previously-written text. I don't believe gnuplot has
a terminal that both

- produces output as text on the console

- uses console control characters to overwrite previous output

So I don't think what you're asking for is possible. But I cannot
believe you actually want it. Why wouldn't you use any of the graphical
terminals?

**Comment by NightMachinary** [comment]
Ok, thanks.

> Why wouldn't you use any of the graphical
terminals?

GUIs are slow, hard to window manage, do not work remotely, ... .
