### ISSUE TITLE
Should be able to read the tic labels from the data

### ISSUE THREAD

**Issue by falves1** [dkogan/feedgnuplot#41]
My data is 
Address Minutes
8.19.245.84 4853.30
8.19.245.83 4797.70
8.19.245.78 4221.10
8.19.245.77 4170.60
8.19.245.62 3382.00
8.19.245.61 3348.30
8.19.245.72 1774.40
8.19.245.71 1750.70
8.19.245.70 1065.00
8.19.245.69 1057.80
8.19.245.88 1000.80
8.19.245.87 955.40
and a need  a simple histogram to compare each IP. 
I tried with
feedgnuplot --histo 0 --binwidth 0.1 --hardcopy /api/tst.pn

and get the wrong image

![image](https://user-images.githubusercontent.com/6633287/107277087-f44bb780-6a21-11eb-9ac6-112cf20a0f68.png)

Instead, I should get something similar to 
![image](https://user-images.githubusercontent.com/6633287/107277248-21986580-6a22-11eb-94c2-e5d5456ca648.png)
but of course showing the labels under each column
what am I doing wrong?

**Comment by dkogan** [comment]
Ah, I see what you're trying to do. This is not a "histogram", but a bar chart. You can do it in `feedgnuplot`, but currently there's no nice support for tic labels that come from a data file, which is what you're trying to do. Let me see if I can add something this week. Leaving this issue open in the meantime.

**Comment by dkogan** [comment]
I just added some initial support for this. Will write the documentation and do a release in a week or two, but in the meantime, you can use it if you check out the latest version of the script from git. With your data in `/tmp/dat`:

```
< /tmp/dat \
tail -n +2 | \
feedgnuplot \
  --xticlabels \
  --with 'boxes fill solid border lt -1' \
  --hardcopy /tmp/tst.png
```

![tst](https://user-images.githubusercontent.com/170011/107479861-8b069a00-6b30-11eb-894a-b27c35bf9509.png)

**Comment by dkogan** [comment]
This is done, and demoed in the guide: https://github.com/dkogan/feedgnuplot/blob/master/guide/guide.org

I'm closing the issue. Please re-open if something doesn't work.
