### ISSUE TITLE
How to send input to feedgnuplot from a different shell

### ISSUE THREAD

**Issue by vapniks** [dkogan/feedgnuplot#46]
If I run feedgnuplot in one of my tmux windows like this:
```
> feedgnuplot --terminal dumb --exit
```
I can enter some numbers, and then press Ctrl+d and it will print a graph.
But if instead I trying sending output to its STDIN file descriptor from another shell, e.g:
```
echo "1\n2\n3\n" > /proc/$(pgrep feedgnuplot)/fd/0
```
and then pressing Ctrl+d in the feedgnuplot terminal/tmux window, then I get this error:
```
gnuplot> plot
              ^
         line 0: function to plot expected
```
If, before pressing Ctrl+d I type `print` and `exit` into the feedgnuplot window (directly, not via /proc), like this:
```
1
2
3
print
enter
```
then it works, and prints a graph.
But if I try sending those commands along with the data via /proc I get the same error:
```
echo "1\n2\n3\nprint\nexit" > /proc/$(pgrep feedgnuplot)/fd/0
```
In the feedgnuplot window:
```
gnuplot> plot
              ^
         line 0: function to plot expected
```
What's going on here? 
How can I send input to feedgnuplot from a different shell?

**Comment by vapniks** [comment]
No, I'm not wrapping feedgnuplot, I'm wrapping another repl and trying to pipe the output to feedgnuplot using a filter I wrote: https://github.com/vapniks/rlwrap_extras/blob/main/filters/pipeto_macro
The piping seems to work fine with other shell commands, but when I try to pipe a list of numbers to feedgnuplot it just hangs and I have to SIGKILL it. I'm trying to figure out what's going on.

**Comment by dkogan** [comment]
OK. This is a bit too involved for me to dig into it. feedgnuplot does
nothing interesting here, so it shouldn't act any differently. If you
want to debug, first figure out if you do or do not have a tty. do ls -l
on the feedgnuplot stdin, or put in an isatty() call. I'd avoid messing
with a tty, if you can.
