### ISSUE TITLE
How to add comands after plot

### ISSUE THREAD

**Issue by mirek23** [dkogan/feedgnuplot#50]
Hello Dima,

I have started to use the feedgnuplot. What is the option to passed the commands from feedgnuplot to gnuplot after:
plot '-' 
when I use the option --with "every ::4::300" it does:
**plot '-' notitle with every ::4::300**
I want to achive:
**plot '-' every ::4::300 notitle**

Best Regards
Mirek

**Comment by dkogan** [comment]
Look at feedgnuplot --every

**Comment by mirek23** [comment]
Hi Dima,

Thanks for your quick answer.
I have tried all possible options and I am not able to tell feedgnuplot to pass every ::4::300 to gnuplot as such that ts is placed after plot '-' 
to get 
**plot '-' every ::4::300 notitle**

Maybe there is an option to substitute notitle with every ::4::300

Best Regards
Mirek

**Comment by dkogan** [comment]
The manpage says that the --every option is given as

  --every curveID factor

So you must specify the curve ID for each "every". And it works:

  $ seq 5 | feedgnuplot --every 0 '::4::300' --dump

  set grid
  set boxwidth 1
  histbin(x) = 1 * floor(0.5 + x/1)
  plot '-'  every ::4::300   notitle  
  1  1
  2  2
  3  3
  4  4
  5  5
  e

Does this help?

**Comment by dkogan** [comment]
Nothing to do here. Closing
